const FEEDBACK_DIALOG = 'FEEDBACK_DIALOG';
const STAFFING_DIALOG = 'STAFFING_DIALOG';
const CONTACT_DIALOG = 'CONTACT_DIALOG';
const HAS_JD_DIALOG = 'HAS_JD_DIALOG';
const NO_JD_DIALOG = 'NO_JD_DIALOG';

module.exports = {
    FEEDBACK_DIALOG,
    STAFFING_DIALOG,
    CONTACT_DIALOG,
    HAS_JD_DIALOG,
    NO_JD_DIALOG
};
