const FEEDBACK_DIALOG = 'FEEDBACK_DIALOG';
const STAFFING_DIALOG = 'STAFFING_DIALOG';
const CONTACT_DIALOG = 'CONTACT_DIALOG';
const HAS_JD_DIALOG = 'HAS_JD_DIALOG';
const NO_JD_DIALOG = 'NO_JD_DIALOG';
const COMMON_JD_DIALOG = 'COMMON_JD_DIALOG';
const SELECTED_OTHER_DIALOG = 'SELECTED_OTHER_DIALOG';
const YES_TOGGLE_LIVE = 'YES_TOGGLE_LIVE';
const OTHER_SKILLSET_DIALOG = 'OTHER_SKILLSET_DIALOG';

module.exports = {
    FEEDBACK_DIALOG,
    STAFFING_DIALOG,
    CONTACT_DIALOG,
    HAS_JD_DIALOG,
    NO_JD_DIALOG,
    COMMON_JD_DIALOG,
    SELECTED_OTHER_DIALOG,
    YES_TOGGLE_LIVE,
    OTHER_SKILLSET_DIALOG
};
